return {
	-- "saghen/blink.cmp",
	-- lazy = false, -- lazy loading handled internally
	-- -- optional: provides snippets for the snippet source
	-- -- dependencies = "rafamadriz/friendly-snippets",
	--
	-- dependencies = {
	-- 	-- "hrsh7th/cmp-buffer", -- source for text in buffer
	-- 	-- "hrsh7th/cmp-path", -- source for file system paths
	-- 	-- "L3MON4D3/LuaSnip", -- snippet engine
	-- 	-- "saadparwaiz1/cmp_luasnip", -- for autocompletion
	-- 	"rafamadriz/friendly-snippets", -- useful snippets
	-- 	-- "onsails/lspkind.nvim", -- vs-code like pictograms
	-- },
	--
	-- -- use a release tag to download pre-built binaries
	-- version = "v0.*",
	-- -- OR build from source, requires nightly: https://rust-lang.github.io/rustup/concepts/channels.html#working-with-nightly-rust
	-- -- build = 'cargo build --release',
	--
	-- opts = {
	-- 	keymap = {
	-- 		-- show = "<M-space>",
	-- 		hide = "<C-e>",
	-- 		accept = "<CR>",
	-- 		-- accept = "<Enter>",
	-- 		select_prev = { "<C-p>" },
	-- 		select_next = { "<C-n>" },
	--
	-- 		show_documentation = {},
	-- 		hide_documentation = {},
	-- 		scroll_documentation_up = "<C-b>",
	-- 		scroll_documentation_down = "<C-f>",
	--
	-- 		-- snippet_forward = "<Up>",
	-- 		-- snippet_backward = "<Down>",
	-- 	},
	-- 	highlight = {
	-- 		-- sets the fallback highlight groups to nvim-cmp's highlight groups
	-- 		-- useful for when your theme doesn't support blink.cmp
	-- 		-- will be removed in a future release, assuming themes add support
	-- 		use_nvim_cmp_as_default = true,
	-- 	},
	-- 	-- set to 'mono' for 'Nerd Font Mono' or 'normal' for 'Nerd Font'
	-- 	-- adjusts spacing to ensure icons are aligned
	-- 	nerd_font_variant = "Nerd Font Mono",
	--
	-- 	-- experimental auto-brackets support
	-- 	-- accept = { auto_brackets = { enabled = true } }
	--
	-- 	-- experimental signature help support
	-- 	-- trigger = { signature_help = { enabled = true } }
	-- },
}
